### ISSUE TITLE
10-set0-1,2.log

### ISSUE THREAD

**Issue by qwer904** [ut-vision/S2DHand#2]
Your work is awesome, but when I run the visualize.py file I get an error, the error is as follows：
Traceback (most recent call last):
  File "visualize.py", line 119, in <module>
    visualize_3d_joints(sample_idx, args.checkpoint, eid=args.evaluate_id, setup=setup, pair=pair)
  File "visualize.py", line 38, in visualize_3d_joints
    lines = open(log).readlines()
NotADirectoryError: [Errno 20] Not a directory: 'data/S2DHand-pretrain/ckp_detnet_37.pth/10-set0-1,2.log'
May I ask where you put your "10-set0-1,2.log" file?

**Comment by MickeyLLG** [comment]
The log file is automatically generated by testing and no existing log file is provided in this project.
For example, kindly run
```bash
python3 adapt_detnet_dual.py -trs ah -tes ah --evaluate -eid 37 --gpus 0 --pic -1 --checkpoint pretrain --setup 0 --pair 1,3
```
and the log file `37-set0,1,3.log` should be under `pretrain/evaluation/ah`.
Then, please run `visualize.py` again by modifying its arguments accordingly.

If you think testing takes a long time, it is okay to set `--pic` with a small value.

**Comment by qwer904** [comment]
Thank you for your answer。But this file does not exist “ train_detnet_dual.py”

**Comment by MickeyLLG** [comment]
Sorry, it should be adapt_detnet_dual.py. I have revised the above response.
