### ISSUE TITLE
During inference, why there are requirements to provide the valid(joint  valid) information from annotation? 

### ISSUE THREAD

**Issue by warmheartHoward** [ut-vision/S2DHand#4]
I try to apply your weight to my own stereo scenario,  but during the evaluate process, i found out there are  requirements to provide the joints valid information when doing the merge for two predictions. but the valid information come from the annotations.  
<img width="919" alt="image" src="https://github.com/ut-vision/S2DHand/assets/46333667/a9af329c-b94f-4e04-b8a3-d8796cebd05b">
why?

**Comment by MickeyLLG** [comment]
Yes, we use valid label from the annotation, which indiactes the visibility of each joint. Such usage is actually common in existing studies.
However, it is also okay to set the valid information all-one matrices.
