### ISSUE TITLE
adapt_detnet_dual.py not working very well (+@)

### ISSUE THREAD

**Issue by giesth39** [ut-vision/S2DHand#5]
Hi

I am interested in the S2DHand challenge, so i was trying to run the adapt_detnet_dual.py file.
there is an brief index of the situation i'm facing with

1. i changed the data name(since from google drive i got test-iccv2023)
2. getting ValueError: cannot reshape array of size 1 into shape (42,)
3. 'test_ego_data.json' file shows null in 'joint_valid' and 'keypoints'
+@ also getting error in calc_metrics.py, too.

since the assemblyhands dataset github says to organize the dataset like;

- ${DATA_DIR}
    - images
        - ego_images_rectified
            - split: {test, train, val}        
    - videos
        - exo_videos_rectified
            - nusar-2021_*
    - annotations
        - skeleton.txt
        - split: {demo, test, train, val}  
            - assemblyhands_${split}_ego_calib_v1-1.json
            - assemblyhands_${split}_ego_data_v1-1.json
            - assemblyhands_${split}_joint_3d_v1-1.json

 and the S2DHand only requires images and annotation, i've changed the googledrive test-iccv2023 folder like;
 
      -test-iccv2023
           - assemblyhands_test_ego_calib_iccv2023_v1-1.json
           - assemblyhands_test_abs_depth_iccv2023-v1-3.json
           - assmeblyhands_test_ego_data_iccv2023-v1-3.json
           - assemblyhands_test_exo_calib_v1-1.json
           - templates
                 -assemblyhands_test_joint3d_iccv23-v1-3_pred_template.json
to 
        test-iccv2023
           - assemblyhands_test_ego_calib_v1-1.json
           - assemblyhands_test_abs_depth_v1-1.json
           - assmeblyhands_test_ego_data_v1-1.json
           - assemblyhands_test_exo_calib_v1-1.json
           -assemblyhands_test_joint3d_v1-1.json

and then tried the code

python3 adapt_detnet_dual.py -trs ah -tes ah --evaluate -eid 37 --gpus 0 --pic -1 --checkpoint pretrain --setup 0 --pair 1,3

and i got
![S2DHands_error_message](https://github.com/ut-vision/S2DHand/assets/174769290/56435675-2dac-44d8-bf99-0462e400155d)

also, if i run
python3 calc_metrics.py --checkpoint in_dataset_adapt/evaluation/ah --setup 0 --pair 1,2

I will get ZeroDivisionError: division by zero from the line164 in calc_metrics.py
print(f'total:{num}, mean Mono-M:{mono / num:.2f}, mean Dual-M:{merge / num:.2f}')

Can i get some help about this?

+) should i make a 'pretrain' directory under 'S2DHands' to run cp ${DATA_DIR}/S2DHand-pretrain/* pretrain  ??

**Comment by MickeyLLG** [comment]
Hi, thanks for being interested in our work. 
Your situation is because the testing annotations of AssemblyHands is not released. The "test-iccv2023" files are for the workshop challenge last year and thus have no ground-truth information. To run our code, I recommend to use validation set instead.
Specifically, you can revise the `data_split` arguments to `data_split='val'` in `adapt_detnet_dual.py` (Lines [144](https://github.com/ut-vision/S2DHand/blob/a3d14c27553330709056b414feec020fb1dbf681/adapt_detnet_dual.py#L144) and [219](https://github.com/ut-vision/S2DHand/blob/a3d14c27553330709056b414feec020fb1dbf681/adapt_detnet_dual.py#L219)). The validation set has ground-truth annotations so the code should be runnable.
Of course, you may also contact the author of AssemblyHands dataset for the access of test set annotations.

+) Yes, please `mkdir pretrain` before copying. The `pretrain` directory has been updated to this repository.
I have updated the README according to your issues. Feel free to add comments if there is any question.

**Comment by giesth39** [comment]
Hi, let me ask you just a few more questions;

i tried 
python3 visualize.py --checkpoint pretrain/evaluation/ah -eid 37 --sample_idx 0 --setup 0 --pair 1,3

1. (I've changed     in_dataset_adapt      to        pretrain      since there is no 37-set0-1,3 log in in_dataset_adapt folder
when i tried
python3 adapt_detnet_dual.py -trs ah -tes ah --root_idx 0 --pic 1024 --resume -eid 37 --epochs 10 --start_epoch 1 --gpus 0 --checkpoint in_dataset_adapt --setup 0 --pair 1,2
and
python3 adapt_detnet_dual.py -trs ah -tes ah --evaluate -eid 37 --gpus 0 --pic -1 --checkpoint pretrain --setup 0 --pair 1,3.
the former would output logs like 1-set0-1,2.log ... 10-set0-1,2.log in in_dataset_adapt/evaluation/ah folder, and the latter would output log 37-set0-1,3.log in pretrain/evaluation/ah folder.)

2. (also, i changed crop root from './data/assemblyhands_crop/images/ego_images_rectified/test/' to './data/assemblyhands_crop/images/ego_images_rectified/val/', since i changed data_split ='val'.)

but since i didn't have a display on the terminal where i was trying the command, i used jupyter notebook to run the visualize code.

i changed the crop_root from /test/ to /val/, since i did
python3 adapt_detnet_dual.p i didn't have a display on the terminal where i was trying the command, i used jupyter notebook to run the visualize code.

![S2DHands_jupnote1y -trs ah -tes ah --evaluate -eid 37 --gpus 0 --pic -1 --checkpoint pretrain --setup 0 --pair 1,3 
on the 'val' folder

![S2DHands_jupnote1](https://github.com/user-attachments/assets/4a3689ae-d46a-483b-804e-c9c49f98d136)
![S2DHands_jupnote2](https://github.com/user-attachments/assets/72833ec3-5ea0-4295-84db-9fa7b1bcac68)
![S2DHands_jupnote3](https://github.com/user-attachments/assets/333218d3-e34d-4af4-8e4b-d66793287e45)
yeah, but i got the result like the image 3.

i wonder what would be the problem about the visualization. plus, when i tried print(kp),
i get
[[  -41   432     0]
 [ -588   700   -16]
 [-3075  2343    -5]
 [ 2565 -1444     9]
 [ 1605  -956    17]
 [  607   544    32]
 [  332   476    70]
 [  343   365    77]
 [  350   272    76]
 [  284   545    47]
 [  228   393    84]
 [  243   293    84]
 [  239   213    80]
 [  140   494    56]
 [  131   309    76]
 [  185   157    52]
 [  273   -71    33]
 [   26   460    62]
 [   54   307    71]
 [   74   185    54]
 [   89    83    41]]
[[-159  -85    0]
 [ -79 -398   23]
 [   1 -246   51]
 [  15 -201   76]
 [  13 -196   95]
 [ 680 -380   21]
 [ 562 -196   39]
 [ 344 -128   60]
 [ 247  -91   74]
 [1054  -88   14]
 [ 470  -39   43]
 [ 229  -43   71]
 [ 147  -42   92]
 [ 882  241   15]
 [ 224   38   52]
 [  78   -6   79]
 [   8  -35   84]
 [ 542  402   18]
 [ 121   90   53]
 [  35   37   65]
 [ -16    4   70]]

and also i got same print(kp) result when i ran in terminal.

Could you tell me what would be the problem?
